# Generated by Django 2.1.7 on 2020-06-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardRelitionship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='玩家', max_length=10)),
                ('PersonId', models.IntegerField(default=1)),
                ('MonsterId', models.IntegerField(default=0)),
                ('cardId', models.IntegerField()),
                ('using', models.IntegerField(default=0)),
            ],
        ),
    ]
