# Generated by Django 2.1.7 on 2020-06-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('funcName', models.CharField(max_length=40)),
                ('consume', models.IntegerField(default=10)),
                ('func', models.CharField(max_length=100)),
                ('returnBloodValue', models.IntegerField()),
                ('returnMagicValue', models.IntegerField()),
                ('damageValue', models.IntegerField()),
                ('protect', models.IntegerField()),
            ],
        ),
    ]
